import json
import sys,requests

API_KEY="c6d06cabc33be82f1cb7ba09c5698df9"  #Api key can be generated by logging into openweathermap and generating the key.
BASE_URL = "https://api.openweathermap.org/data/2.5/weather?"
weather_data={}
temp=0
try:
	url=BASE_URL+'q='+sys.argv[1]+'&appid='+API_KEY
	headers={'Accept':'application/json'} # to accept only json data
	
	response=requests.get(url,headers=headers)
	data=response.text  # return a json data
	
	
	weather_data=json.loads(data)  # converts json string to python
	temp=weather_data['main']['temp']-273.15
	print('Today weather in '+sys.argv[1]+' is '+str(temp)+' Degree Celsius')
	
except TypeError:
	print('Some error has occured')

